import { POST } from "@/app/api/Authentication/Login/route";
import { ROLES } from "../constants/roles";
import { API_PATHS } from "./APIPaths";
import { GET } from "@/app/api/Authentication/user/route";




export const API_PATH_PERMISSION:Record<string, any> = {
    POST:{
        [API_PATHS.USER_LOGIN]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.USER_SIGNUP]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.BLOOD_REQUEST_CREATE]: [ROLES.RECIPIENT],
    },
    GET:{
        [API_PATHS.USER_ME]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.USER_AVAILABILITY]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.USER_LOCATION]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.USER_ROLE]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.USER_PROFILE]: [ROLES.DONOR, ROLES.RECIPIENT],

    },
    PUT:{
        [API_PATHS.USER_VERIFY]: [ROLES.DONOR, ROLES.RECIPIENT],
        [API_PATHS.BLOOD_REQUEST_CANCEL]: [ROLES.RECIPIENT],
        [API_PATHS.BLOOD_REQUEST_CONFIRM]: [ROLES.RECIPIENT],
        [API_PATHS.BLOOD_REQUEST_UPDATE]: [ROLES.RECIPIENT],
        [API_PATHS.BLOOD_REQUEST_MANAGE]: [ROLES.RECIPIENT],

    },
    DELETE:{
        [API_PATHS.USER_LOGOUT]: [ROLES.DONOR, ROLES.RECIPIENT],
    }
}